-- 코드를 입력하세요
-- USED_GOODS_BOARD : BOARD_ID, WRITER_ID, TITLE, CONTENTS, PRICE, CREATED_DATE, STATUS, VIEWS
-- USED_GOODS_REPLY : REPLY_ID, BOARD_ID, WRITER_ID, CONTENTS, CREATED_DATE

-- TITLE, CONTENTS 와 같이 2개의 테이블에서 모두 사용될 수 있는 컬럼의 경우 확인

# SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE 
# FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
# WHERE B.CREATED_DATE BETWEEN  '2022-10-01' AND  '2022-10-30'
# ORDER BY B.CREATED_DATE, B.TITLE

# SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, B.CONTENTS, 
#         DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE 
# FROM USED_GOODS_BOARD B , USED_GOODS_REPLY R 
# WHERE  B.BOARD_ID = R.BOARD_ID AND 
#         B.CREATED_DATE BETWEEN  '2022-10-01' AND  '2022-10-31'
# ORDER BY B.CREATED_DATE, B.TITLE

-- 풀이 : FROM 먼저 적기
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, 
        DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE 
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE A.BOARD_ID = B.BOARD_ID AND
        A.CREATED_DATE BETWEEN  ('2022-10-01') AND  ('2022-10-31')
ORDER BY B.CREATED_DATE, A.TITLE