-- 코드를 입력하세요
-- FIRST_HALF : SHIPMENT_ID, FLAVOR, TOTAL_ORDER
-- ICECREAM_INFO : FLAVOR, INGREDITENT_TYPE
SELECT  INGREDIENT_TYPE, sum(TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF JOIN ICECREAM_INFO
ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER 